name:               "蒋世伟"
description:        "WEB/系统/安全"

url:                ""
author:             "owen"
email:              "owen.jsw@icloud.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "Owen_JSW"
email:              "owen.jsw@icloud.com"
github:             "owenjsw"
zhihu:              "people/owen-jiang-28/activities"
facebook:           "profile.php?id=100010773995985"

disqus_shortname:   "蒋世伟"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
